---
latitude: 40.761505
longitude: -73.982593
map_zoom: 12
name: The Michelangelo
email: reservations@michelangelohotel.com
phone_number: "+1 212 7651900"
address:
  street1: 152 West 51st Street
  state: New York
  city: NY
  zip_code: 10019
  country: USA
default_currency: USD
default_timezone: America/New_York
_hotel_id: NYCMIC
_portal_id: michelangelohotel
__EDITABLE_FIELDS__:
  name:
    required: true
  logo:
    type: image
  logo_secondary:
    type: image
  email:
    type: string
  email_concierge:
    type: string
  phone_number:
    type: string
  alternate_number:
    type: string
  concierge_number:
    type: string
  default_currency:
    required: true
  address:
    type: complex
    fields:
      street1:
        type: string
      state:
        type: string
      city:
        type: string
      zip_code:
        type: string
      country:
        type: string
  starhotels_logo:
    type: image
  lifestyle_logo:
    type: image
  iprefer_logo:
    type: image
  traveller_logo:
    type: image
  handy_logo:
    type: image
  map_zoom:
    type: integer
  latitude:
    type: float
  longitude:
    type: float
get_directions_url: https://goo.gl/maps/wDPkcHicBJu58JB3A
email_concierge: themichelangelo@cityexperts.com
alternate_number: "+1 212 5416604"
concierge_number: "+1 212-261-8920"
site_url: https://www.michelangelohotel.com/
_root_path: https://rt3api-prd.ttaws.com
_ttweb_plugins_version: v3.2.3
logo:
  name: themichelangelo-white
  content_type: image/svg+xml
  date_added: 2019-07-02-081151
  format: 
  url: "//res.cloudinary.com/traveltripperweb/raw/upload/v1562069511/h5cexwy85w5oz5woukmc.svg"
  url_raw: "//res.cloudinary.com/traveltripperweb/raw/upload/v1562069511/h5cexwy85w5oz5woukmc.svg"
  resource_type: raw
  size: 16948
  path: "//res.cloudinary.com/traveltripperweb/raw/upload/v1562069511/h5cexwy85w5oz5woukmc.svg"
  file_size: 
  alt: The Michelangelo New York
  caption: ''
  description: ''
logo_secondary:
  name: themichelangelo-bronze
  content_type: image/svg+xml
  date_added: 2019-07-02-081219
  format: 
  url: "//res.cloudinary.com/traveltripperweb/raw/upload/v1562069539/teqwsryijcum3undsflp.svg"
  url_raw: "//res.cloudinary.com/traveltripperweb/raw/upload/v1562069539/teqwsryijcum3undsflp.svg"
  resource_type: raw
  size: 16948
  path: "//res.cloudinary.com/traveltripperweb/raw/upload/v1562069539/teqwsryijcum3undsflp.svg"
  file_size: 
  alt: The Michelangelo New York
  caption: ''
  description: ''
starhotels_logo:
  name: star-hotels
  content_type: image/png
  date_added: 2019-07-09-045240
  url_thumb: "//res.cloudinary.com/traveltripperweb/image/upload/c_fill,g_faces,h_140,w_140/v1562662360/yltlvpr5njlq2xvhgsjp.png"
  url_xsmall: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_300,w_300/v1562662360/yltlvpr5njlq2xvhgsjp.png"
  url_small: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_768,w_768/v1562662360/yltlvpr5njlq2xvhgsjp.png"
  url_medium: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_992,w_992/v1562662360/yltlvpr5njlq2xvhgsjp.png"
  url_large: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_1200,w_1200/v1562662360/yltlvpr5njlq2xvhgsjp.png"
  url_xlarge: "//res.cloudinary.com/traveltripperweb/image/upload/c_limit,h_1920,w_1920/v1562662360/yltlvpr5njlq2xvhgsjp.png"
  url: "//res.cloudinary.com/traveltripperweb/image/upload/c_limit,h_2500,w_2500/v1562662360/yltlvpr5njlq2xvhgsjp.png"
  width: 308
  height: 72
  format: png
  url_raw: "//res.cloudinary.com/traveltripperweb/image/upload/v1562662360/yltlvpr5njlq2xvhgsjp.png"
  resource_type: image
  size: 18108
  path: "//res.cloudinary.com/traveltripperweb/image/upload/c_limit,h_2500,w_2500/v1562662360/yltlvpr5njlq2xvhgsjp.png"
  file_size: 
  alt: Star Hotels
lifestyle_logo:
  name: preferred-lifestyle-black
  content_type: image/svg+xml
  date_added: 2019-07-09-045315
  format: 
  url: "//res.cloudinary.com/traveltripperweb/raw/upload/v1562662395/tjfmqlzurgknwti5mgko.svg"
  url_raw: "//res.cloudinary.com/traveltripperweb/raw/upload/v1562662395/tjfmqlzurgknwti5mgko.svg"
  resource_type: raw
  size: 16861
  path: "//res.cloudinary.com/traveltripperweb/raw/upload/v1562662395/tjfmqlzurgknwti5mgko.svg"
  file_size: 
  alt: Preferred Lifestyle
iprefer_logo:
  name: iprefer-black
  content_type: image/svg+xml
  date_added: 2019-07-09-045353
  format: 
  url: "//res.cloudinary.com/traveltripperweb/raw/upload/v1562662433/ttqewi91zjt8p8t8g0yf.svg"
  url_raw: "//res.cloudinary.com/traveltripperweb/raw/upload/v1562662433/ttqewi91zjt8p8t8g0yf.svg"
  resource_type: raw
  size: 13160
  path: "//res.cloudinary.com/traveltripperweb/raw/upload/v1562662433/ttqewi91zjt8p8t8g0yf.svg"
  file_size: 
  alt: I Prefer
