---
latitude: 32.283875
longitude: -64.786403
map_zoom: 12
get_directions_url: https://goo.gl/maps/wDPkcHicBJu58JB3A
name: The Michelangelo New York
email: reservations@michelangelohotel.com
email_concierge: themichelangelo@cityexperts.com
phone_number: +1 212 7651900
alternate_number: +1 212 5416604
concierge_number: +1 212-261-8920
address:
  street1: 152 West 51st Street
  state: New York
  city: NY
  zip_code: 10019
default_currency: USD
default_timezone: America/New_York
_hotel_id:
_portal_id:
__EDITABLE_FIELDS__:
  name:
    required: true
  logo:
    type: image
  logo_secondary:
    type: image
  email:
    type: string
  email_concierge:
    type: string
  phone_number:
    type: string
  alternate_number:
    type: string
  concierge_number:
    type: string
  default_currency:
    required: true
  address:
    type: complex
    fields:
      street1:
        type: string
      state:
        type: string
      city:
        type: string
      zip_code:
        type: string
  map_zoom:
    type: integer
  latitude:
    type: float
  longitude:
    type: float
site_url: https://www.michelangelohotel.com/
_root_path: https://rt3api-prd.ttaws.com
_ttweb_plugins_version: v3.2.3
logo:
  name: logo-white
  content_type: image/png
  date_added: 2019-06-03-021349
  url_thumb: "//res.cloudinary.com/traveltripperweb/image/upload/c_fill,g_faces,h_140,w_140/v1559542429/ki7iazbth8wxggoi3cdg.png"
  url_xsmall: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_300,w_300/v1559542429/ki7iazbth8wxggoi3cdg.png"
  url_small: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_768,w_768/v1559542429/ki7iazbth8wxggoi3cdg.png"
  url_medium: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_992,w_992/v1559542429/ki7iazbth8wxggoi3cdg.png"
  url_large: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_1200,w_1200/v1559542429/ki7iazbth8wxggoi3cdg.png"
  url_xlarge: "//res.cloudinary.com/traveltripperweb/image/upload/c_limit,h_1920,w_1920/v1559542429/ki7iazbth8wxggoi3cdg.png"
  width: 474
  height: 84
  format: png
  url: "//res.cloudinary.com/traveltripperweb/image/upload/v1559542429/ki7iazbth8wxggoi3cdg.png"
  resource_type: image
  size: 23991
  path: "//res.cloudinary.com/traveltripperweb/image/upload/v1559542429/ki7iazbth8wxggoi3cdg.png"
  file_size:
  alt: logo-white
logo_secondary:
  name: logo-color
  content_type: image/png
  date_added: 2019-06-03-021417
  url_thumb: "//res.cloudinary.com/traveltripperweb/image/upload/c_fill,g_faces,h_140,w_140/v1559542457/qcpbvl2jzzxfygidtehh.png"
  url_xsmall: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_300,w_300/v1559542457/qcpbvl2jzzxfygidtehh.png"
  url_small: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_768,w_768/v1559542457/qcpbvl2jzzxfygidtehh.png"
  url_medium: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_992,w_992/v1559542457/qcpbvl2jzzxfygidtehh.png"
  url_large: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_1200,w_1200/v1559542457/qcpbvl2jzzxfygidtehh.png"
  url_xlarge: "//res.cloudinary.com/traveltripperweb/image/upload/c_limit,h_1920,w_1920/v1559542457/qcpbvl2jzzxfygidtehh.png"
  width: 444
  height: 76
  format: png
  url: "//res.cloudinary.com/traveltripperweb/image/upload/v1559542457/qcpbvl2jzzxfygidtehh.png"
  resource_type: image
  size: 24264
  path: "//res.cloudinary.com/traveltripperweb/image/upload/v1559542457/qcpbvl2jzzxfygidtehh.png"
  file_size:
  alt: logo-color
