---
latitude: 40.761505
longitude: -73.982593
map_zoom: 12
name: The Michelangelo New York
email: reservations@michelangelohotel.com
phone_number: "+1 212 7651900"
address:
  street1: 152 West 51st Street
  state: New York
  city: NY
  zip_code: 10019
default_currency: USD
default_timezone: America/New_York
_hotel_id: 
_portal_id: 
__EDITABLE_FIELDS__:
  name:
    required: true
  logo:
    type: image
  logo_secondary:
    type: image
  email:
    type: string
  email_concierge:
    type: string
  phone_number:
    type: string
  alternate_number:
    type: string
  concierge_number:
    type: string
  default_currency:
    required: true
  address:
    type: complex
    fields:
      street1:
        type: string
      state:
        type: string
      city:
        type: string
      zip_code:
        type: string
  map_zoom:
    type: integer
  latitude:
    type: float
  longitude:
    type: float
get_directions_url: https://goo.gl/maps/wDPkcHicBJu58JB3A
email_concierge: themichelangelo@cityexperts.com
alternate_number: "+1 212 5416604"
concierge_number: "+1 212-261-8920"
site_url: https://www.michelangelohotel.com/
_root_path: https://rt3api-prd.ttaws.com
_ttweb_plugins_version: v3.2.3
logo:
  name: michelangelo-logo-white
  content_type: image/png
  date_added: 2019-07-02-063449
  url_thumb: "//res.cloudinary.com/traveltripperweb/image/upload/c_fill,g_faces,h_140,w_140/v1562063689/wkekype5qo5kgmz94mbt.png"
  url_xsmall: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_300,w_300/v1562063689/wkekype5qo5kgmz94mbt.png"
  url_small: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_768,w_768/v1562063689/wkekype5qo5kgmz94mbt.png"
  url_medium: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_992,w_992/v1562063689/wkekype5qo5kgmz94mbt.png"
  url_large: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_1200,w_1200/v1562063689/wkekype5qo5kgmz94mbt.png"
  url_xlarge: "//res.cloudinary.com/traveltripperweb/image/upload/c_limit,h_1920,w_1920/v1562063689/wkekype5qo5kgmz94mbt.png"
  url: "//res.cloudinary.com/traveltripperweb/image/upload/c_limit,h_2500,w_2500/v1562063689/wkekype5qo5kgmz94mbt.png"
  width: 378
  height: 144
  format: png
  url_raw: "//res.cloudinary.com/traveltripperweb/image/upload/v1562063689/wkekype5qo5kgmz94mbt.png"
  resource_type: image
  size: 14379
  path: "//res.cloudinary.com/traveltripperweb/image/upload/c_limit,h_2500,w_2500/v1562063689/wkekype5qo5kgmz94mbt.png"
  file_size: 
  alt: Michelangelo New York
  caption: ''
  description: ''
logo_secondary:
  name: michelangelo-logo-color
  content_type: image/png
  date_added: 2019-07-02-063530
  url_thumb: "//res.cloudinary.com/traveltripperweb/image/upload/c_fill,g_faces,h_140,w_140/v1562063731/zcnn5rd3jczaizvzq0vu.png"
  url_xsmall: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_300,w_300/v1562063731/zcnn5rd3jczaizvzq0vu.png"
  url_small: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_768,w_768/v1562063731/zcnn5rd3jczaizvzq0vu.png"
  url_medium: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_992,w_992/v1562063731/zcnn5rd3jczaizvzq0vu.png"
  url_large: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_1200,w_1200/v1562063731/zcnn5rd3jczaizvzq0vu.png"
  url_xlarge: "//res.cloudinary.com/traveltripperweb/image/upload/c_limit,h_1920,w_1920/v1562063731/zcnn5rd3jczaizvzq0vu.png"
  url: "//res.cloudinary.com/traveltripperweb/image/upload/c_limit,h_2500,w_2500/v1562063731/zcnn5rd3jczaizvzq0vu.png"
  width: 378
  height: 144
  format: png
  url_raw: "//res.cloudinary.com/traveltripperweb/image/upload/v1562063731/zcnn5rd3jczaizvzq0vu.png"
  resource_type: image
  size: 23419
  path: "//res.cloudinary.com/traveltripperweb/image/upload/c_limit,h_2500,w_2500/v1562063731/zcnn5rd3jczaizvzq0vu.png"
  file_size: 
  alt: michelangelo-logo-color
  caption: ''
  description: ''
